label.path = Folder-path... 
label.browse = Browse...
label.directory = Choose folder to sort
label.sort = Sort
label.ready = Status: ready
label.finished = Status: Finished! %d moved, %d failed.

info.processed = processed files:  %d Dateien%n
info.skipped = Skipped files: %d Dateien (unbekannte Endung -> 'Sonstiges')%n
info.failed = failed files:       %d Dateien%n
info.failed.infos = Fehlerdetails:
info.done = Sorting finished

warning.notFound = Folder does not exist: 
warning.isFile = Path is not a folder: 

severe.!read = Error while reading folder: 

folder.pictures = Pictures
folder.documents = Documents
folder.tables = Tables
folder.presentations = Presentations
folder.videos = Videos
folder.music = Music
folder.archives = Archives
folder.code = Code
folder.executables = Executables
folder.others = Other